services:
  mongo:
    container_name: nuxt-mongo-server
    image: mongo:3.6
    volumes:
      - /Users/lincenying/web/mongodb/data:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet

  api:
    container_name: nuxt-api-server
    image: lincenying/api-server:${APITAG}
    environment:
      DATABASE_URL: mongodb://mongo:27017
    ports:
      - 4008:4000
    depends_on:
      - mongo
    networks:
      - webnet

  nuxt:
    container_name: nuxt-app-server
    image: lincenying/images-mmf-blog-vite-nuxt:${TAG}
    environment:
      NUXT_ENV_API_URL: http://api:4000
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - api
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 7200:7200
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
